[package]
name = "CounterCrossCall"
version = "0.0.0"

[addresses]
CounterCrossCall = "43239e71ccc047ea2d3752eba79279cf9d091ecb6a04d8cf5103e1e9ae847958"
Counter = "9f53ba21527d32dd88e533946b085f9ab813d8ed40c13bbe2c667ea3a7e2b60f"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
Counter = { local = "../counter" }