[package]
name = "CounterCrossCall"
version = "0.0.0"

[addresses]
CounterCrossCall = "45538d67a76e355d0cd0588631b80f81819dc5daa770f82917030cea98a2b76d"
Counter = "5dfe0e93eed9c2b1bb6bce2c2d2eda1345cbb222a4b5ab4fde6aa35d6540db21"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
Counter = { local = "../counter" }
